FROM apache/spark:3.5.1-python3

USER root

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY src/ /opt/pipeline/src/
COPY config/ /opt/pipeline/config/

ENV PYTHONPATH="/opt/pipeline/src:${PYTHONPATH}"

USER 0